In [8]:
a = int(input("A: "))
b = int(input("B: "))
try:
    res = a/b
    print(res)
except:
    print("Not possible")
print("Done!")

A: 2
B: 0
Not possible
Done!


In [1]:
import numpy as np
flag = int(2)
row,col,row1,col1 = int(0),int(0),int(0),int(0)
def accept():
    print("For Matrix 1")
    row = int(input("Enter rows : "))
    col = int(input("Enter columns: "))
    print("For Matrix 2")
    row1 = int(input("Enter rows : "))
    col1 = int(input("Enter columns: "))
    M1 =np.zeros((row,col))
    M2 =np.zeros((row1,col1))
    if(check(row,col,row1,col1)):
        for i in range(0,row):
            for j in range(0,col):
                M1[i][j] = int(input("M1:"))
        for i in range(0,row1):
            for j in range(0,col1):
                M2[i][j] = int(input("M2:"))
        add(M1,M2)
        sub(M1,M2)
        mult(M1,M2,row,col1,col)
        div(M1,M2,row,col)
    elif(check1(row,col,row1,col1)):
        for i in range(0,row):
            for j in range(0,col):
                M1[i][j] = int(input("M1:"))
        for i in range(0,row1):
            for j in range(0,col1):
                M2[i][j] = int(input("M2:"))
        mult(M1,M2,row,col1,col) 
    else:
        accept()
def check(row,col,row1,col1):
    try:
        m = 1/((row==row1) and (col==col1))
        return m
    except:
        print("Not Equal! For Add,Sub,Div")
        
def check1(row,col,row1,col1):
    try:
        m = 1/(col==row1)
        return m
    except:
        print("Not Equal! For Mul")
        
def add(M1,M2):
    if(check(row,col,row1,col1)):
            print(M1+M2)
def sub(M1,M2):
    try:
        if(check(row,col,row1,col1)):
            print(M1-M2)
    except:
        print("Not Possible!")
def mult(M1,M2,row,col1,col):
        result =np.zeros((row,col1))
        for i in range(0,row):
            for j in range(0,col1):
                for k in range(0,col):
                    result[i][j] += M1[i][k] * M2[k][j]
        print(result)
def div(M1,M2,row,col):
    try:
        for i in range(0,row):
            for j in range(0,col):
                if(M2[i][j] == 0):
                    flag =0
                    raise ZeroDivisionError 
                else:
                    flag = 1
        if(flag ==1):
            print(M1/M2)
    except ZeroDivisionError:
        print("Division Not Possible!")

accept()


For Matrix 1


Enter rows :  2
Enter columns:  2


For Matrix 2


Enter rows :  2
Enter columns:  2
M1: 1
M1: 2
M1: 3
M1: 4
M2: 1
M2: 2
M2: 3
M2: 4


[[2. 4.]
 [6. 8.]]
[[0. 0.]
 [0. 0.]]
[[ 7. 10.]
 [15. 22.]]
[[1. 1.]
 [1. 1.]]
